### ISSUE TITLE
Asymmetric bitstrings

### ISSUE THREAD

**Issue by agata-branczyk** [IBM-Quantum-Prototypes/entanglement-forging#10]
**Is your feature request related to a problem? Please describe.**
With the current version of Entanglement Forging, it's not possible to model open-shell species.

**Describe the solution you'd like**
Having the option to specify different bitstrings for spin-up/spin down orbitals would make it possible to model open-shell species.

**Additional context**
N/A

**Comment by orielkiss** [comment]
I would like to add, that it would be useful for nuclear physics simulations to permit a different number of alpha and beta particle. Usually, orbitals with different angular momentum are weakly correlated and this would permit the application of entanglement forging in this context. 

For example, giving a 12 orbitals Hamiltonian, i would like to split it in a 8 orbitals times a 4 orbitals term.

**Comment by agata-branczyk** [comment]
Thank you for your comment @orielkiss. This is helpful to know when prioritizing which features we can implement!

**Comment by orielkiss** [comment]
Thanks you so much @calebj15 !
